install: composer install

language: php

php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

script:
  - mysql -u root -p < tests/Assets/Create.sql
  - mysql -u root -p < tests/Assets/Data.sql
  - vendor/bin/phpcs --standard=PSR1,PSR2 Soneritics/Database/
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --whitelist Soneritics/ tests/

after_script:
  - php vendor/bin/coveralls -v
